### ISSUE TITLE
English not show up as 2nd language option

### ISSUE THREAD

**Issue by arman86** [mikesteele/dual-captions#82]
Hi. I am running 1.6 on Netflix with the Club de Cuervos show (https://www.netflix.com/watch/80197454). I have Spanish as the primary subtitle:
<img width="232" alt="image" src="https://user-images.githubusercontent.com/30092819/58385547-d5379880-7fa6-11e9-88c8-eb20beb06bf7.png">

with: 
<img width="214" alt="image" src="https://user-images.githubusercontent.com/30092819/58385535-a6b9bd80-7fa6-11e9-80db-2d94a8bc0522.png">

 but then can't get English to show up as a second option:
<img width="295" alt="image" src="https://user-images.githubusercontent.com/30092819/58385492-209d7700-7fa6-11e9-84e8-db793737f002.png">

Any ideas?

**Comment by mikesteele** [comment]
Hey! I'm in Seattle right now visiting a friend until Wednesday, I'll debug
this then!

**Comment by arman86** [comment]
Thanks much. I imagine this may be hard to debug because after a few different attempts (not exactly sure what I had done), English showed up as a secondary option at which point I went to Netflix and changed the primary subtitle to Spanish. Weird.

**Comment by mikesteele** [comment]
I think it's probably due to the background page sending a caption request
message before the content scripts are ready to process it. I added a
"caption request queue" task to v2 which would fix this and I may backport
it to v1.

**Comment by arman86** [comment]
Just let me know when/how you would like me to test the fix.

**Comment by mikesteele** [comment]
Should be fixed in v2, let me know!

**Comment by arman86** [comment]
Neat Mike. I just tried it. 

The auto-detect for languages is nice. The subtitles seem more snappy—not sure if this is for real but it sure seems that way. I can’t figure out when the subtitles show up at the top of the screen vs the bottom but regardless they are legible and I no longer have to move the mouse around. 

The only issue I can see immediately is that the two languages come out the same, then I have to change one. I filed it now as issue 92:
	https://github.com/mikesteele/dual-captions/issues/97 <https://github.com/mikesteele/dual-captions/issues/97>

Much thanks, Arman

**Comment by mikesteele** [comment]
Hi! Glad you noticed the subtitles are snappier, I've been working on improving that. The subtitles go where Netflix decides to put theirs, so top or bottom. Thanks for testing the release so quickly!

**Comment by arman86** [comment]
It is my pleasure. I wish I could do more. Just let me know if you think of anything. I use and appreciate the program very much.

Best, Arman.

**Comment by arman86** [comment]
I loaded v2.0.1. 

Issue persists:


This time it is Spanish on Spanish:


But easy to get to English on English as well just start with English as the initial subtitles and get to:


And you get English doubled:


Best, Arman.

**Comment by mikesteele-drizly** [comment]
Thanks Arman. I'll let you know progress on that bug in the issue you opened #97. I have some higher priority features to roll out first, so a fix won't be in the next few releases, sorry!

**Comment by arman86** [comment]
All good. Thank you for the great program. Please do let me know if there’s anything else in general you’d like me to do/test. 

-Arman
(brief with mstakes from my phone)

**Comment by mikesteele** [comment]
Hi Arman,

I just realized v2.0.3 which adds two new settings to the extension. Check
them out and let me know what you think.

Mike

**Comment by arman86** [comment]
Immediately speaking, the options (especially the Small Text one) look very useful. Let me try it out some variations for a few days and write you a more informed review. 

Thanks and best, Arman.

**Comment by mikesteele** [comment]
Looking forward to it!

**Comment by arman86** [comment]
Hi Mike,

So, after a few days of usage, I can tell you that the new settings are very useful and worked without a hitch. I ended up with Spanish as the primary (big and white) with English as secondary (small and light blue). This helps me focus on Spanish and allows me to quickly isolate English for reference. I don’t have a need for additional options to choose color or size etc. for the primary language. 

Is any interactivity possible? If so, I would love to be able to click (or option-click or some key combination, whatever) to copy the two texts onto the clipboard on their way to Anki--my flashcard program. 

Also, I am curious which languages are supposed to show up in the Second Subtitle menu item? As you know, I always get one option on that menu: the primary subtitle language. 

Best, Arman.
